Fix a compilation issue with uClibc due to a missing include file.
------
In file included from t_auth.c:35:
iperf_api.h:395:77: error: unknown type name ‘va_list’
  395 | void iperf_exit(struct iperf_test *test, int exit_code, const char *format, va_list argp) __attribute__ ((noreturn));
	  |                                                                             ^~~~~~~
iperf_api.h:33:1: note: ‘va_list’ is defined in header ‘<stdarg.h>’; did you forget to ‘#include <stdarg.h>’?
   32 | #include <setjmp.h>
  +++ |+#include <stdarg.h>
   33 | #include <stdio.h>
-----